ratul - 06292018.zip
Updates as of 6/29/2018:
General: all pages have same font color, standard hyperlinks, smaller pics to load faster, font face changed to standard Calibri
Home Page: Contents updated, pictures with smaller size to load faster
Events Page: Contents updated, pictures with smaller size to load faster
About Us Page: Contents updated
Coming Soon: ready
Error: newly introduced
Gallery: contents needed to develop
Contact Us: contents needed to develop